import Link from 'next/link';

type VersionCard = {
  id: string;
  name: string;
  href: string;
  tagline: string;
  description: string;
  inputType: string;
  outputType: string;
  highlight?: string;
};

const versions: VersionCard[] = [
  {
    id: 'AF-01',
    name: 'Basic Generator',
    href: '/ag-aff-01',
    tagline: 'Simple theme-based generation',
    description: 'The fastest path to affirmations. Select themes, optionally add context, and get 10 personalized affirmations instantly.',
    inputType: 'Theme selection',
    outputType: 'Batch of 10',
  },
  {
    id: 'GT-01',
    name: 'Good Ten',
    href: '/ag-good-ten',
    tagline: 'Quality-focused generation',
    description: 'Same input as AF-01, but uses detailed psychological criteria for higher-quality, more thoughtfully crafted affirmations.',
    inputType: 'Theme selection',
    outputType: 'Batch of 10',
    highlight: 'Quality focused',
  },
  {
    id: 'FP-01',
    name: 'Full Process',
    href: '/full-process',
    tagline: 'Guided 3-step discovery',
    description: 'A wizard helps you clarify what you need: focus area, challenges, and tone. Then review affirmations via swipe cards.',
    inputType: '3-step wizard',
    outputType: 'Swipe cards',
  },
  {
    id: 'FP-02',
    name: 'Full Process 2',
    href: '/full-process-2',
    tagline: 'Feedback-aware generation',
    description: 'Same wizard as FP-01, but the AI learns from both what you like and skip. Each batch gets better at matching your preferences.',
    inputType: '3-step wizard',
    outputType: 'Adaptive swipe',
    highlight: 'Learns from swipes',
  },
  {
    id: 'FP-03',
    name: 'Full Process 3',
    href: '/full-process-3',
    tagline: 'Chat-first onboarding',
    description: 'Same feedback-learning as FP-02, but with a conversational UX instead of a wizard. Quick-reply buttons make it feel natural.',
    inputType: 'Chat + choices',
    outputType: 'Swipe cards',
    highlight: 'Chat interface',
  },
  {
    id: 'AP-01',
    name: 'Contextual Mirror',
    href: '/alt-process-1',
    tagline: 'Zero-structure input',
    description: 'Just vent or share freely. The AI extracts context, shows you tags to prove it understood, then generates personalized affirmations.',
    inputType: 'Free text',
    outputType: 'Tags + swipe',
    highlight: 'AI structures for you',
  },
  {
    id: 'AP-02',
    name: 'Reactive Stream',
    href: '/alt-process-2',
    tagline: 'Zero input required',
    description: 'TikTok-style discovery. Affirmations appear instantly - no setup needed. Just swipe and the AI learns your preferences.',
    inputType: 'None (swipe only)',
    outputType: 'Endless stream',
    highlight: 'Instant start',
  },
  {
    id: 'CS-01',
    name: 'Chat Survey',
    href: '/chat-survey',
    tagline: 'Deepest personalization',
    description: 'Have a natural conversation about your challenges and goals. The AI builds a profile and generates deeply personalized affirmations.',
    inputType: 'Conversation',
    outputType: 'Personalized swipe',
    highlight: 'Most personal',
  },
  {
    id: 'FO-01',
    name: 'Full Onboarding',
    href: '/fo-01',
    tagline: 'Complete warm onboarding experience',
    description: 'A 10-step onboarding flow that collects user intention via open text, generates 100 personalized affirmations, and uses swipe selection to build a personal collection.',
    inputType: 'Name + intention',
    outputType: 'Swipe selection',
    highlight: 'Full journey',
  },
  {
    id: 'FO-02',
    name: 'Full Onboarding (Iterative)',
    href: '/fo-02',
    tagline: 'Onboarding that learns from your choices',
    description: 'Same 10-step onboarding as FO-01, but with real iterative improvement. Each batch of affirmations is generated based on what you approved and skipped in previous batches.',
    inputType: 'Name + intention + swipe feedback',
    outputType: 'Progressively personalized affirmations',
    highlight: 'Learns as you swipe',
  },
  {
    id: 'FO-03',
    name: 'Full Onboarding (Gradual)',
    href: '/fo-03',
    tagline: 'Multi-question onboarding with inspiration chips',
    description: 'Warms users up with easy questions before longer input. Uses toggleable inspiration chips alongside open text to reduce friction and collect richer context (feelings, situation, what helps).',
    inputType: 'Multi-step + chips + text',
    outputType: 'Iterative swipe selection',
    highlight: 'Lower friction input',
  },
  {
    id: 'FO-04',
    name: 'Full Onboarding (Dynamic)',
    href: '/fo-04',
    tagline: 'AI-generated discovery screens',
    description: 'Dynamic onboarding where discovery screens are generated by AI in real-time. Each screen adapts based on previous responses, creating a truly personalized journey to affirmations.',
    inputType: 'Dynamic AI-generated prompts',
    outputType: 'Iterative swipe selection',
    highlight: 'Dynamic AI screens',
  },
  {
    id: 'FO-05',
    name: 'Full Onboarding (Sentence Fragments)',
    href: '/fo-05',
    tagline: 'Lower friction with sentence starters + journey summaries',
    description: 'Dynamic discovery with AI-generated sentence fragments that help users express themselves. Includes personalized journey summaries before and after affirmation generation that make users feel truly seen.',
    inputType: 'Free text + sentence fragments',
    outputType: 'Summaries + swipe selection',
    highlight: 'Journey summaries',
  },
];

export default function OverviewPage() {
  return (
    <div className="min-h-screen bg-gray-900 p-8">
      <div className="max-w-6xl mx-auto">
        <header className="mb-8">
          <h1 className="text-3xl font-bold text-white mb-2">Aiffirmation Prototypes</h1>
          <p className="text-gray-400">
            Exploring different approaches to AI-powered affirmation generation
          </p>
        </header>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
          {versions.map((version) => (
            <Link
              key={version.id}
              href={version.href}
              className="group block bg-gray-800 rounded-lg p-6 hover:bg-gray-700 hover:ring-1 hover:ring-purple-500/50 transition-all"
            >
              <div className="flex items-start justify-between mb-2">
                <div>
                  <span className="text-sm font-mono text-purple-400">{version.id}</span>
                  <h2 className="text-xl font-semibold text-white group-hover:text-purple-300 transition-colors">
                    {version.name}
                  </h2>
                </div>
                {version.highlight && (
                  <span className="text-xs bg-purple-500/20 text-purple-300 px-2 py-1 rounded whitespace-nowrap">
                    {version.highlight}
                  </span>
                )}
              </div>

              <p className="text-xs text-purple-400/70 mb-3">{version.tagline}</p>

              <p className="text-sm text-gray-400 mb-5 leading-relaxed">
                {version.description}
              </p>

              <div className="flex gap-6 text-sm">
                <div>
                  <span className="text-gray-500">Input:</span>{' '}
                  <span className="text-gray-300">{version.inputType}</span>
                </div>
                <div>
                  <span className="text-gray-500">Output:</span>{' '}
                  <span className="text-gray-300">{version.outputType}</span>
                </div>
              </div>
            </Link>
          ))}
        </div>

        <footer className="mt-12 pt-8 border-t border-gray-800">
          <h3 className="text-sm font-medium text-gray-400 mb-4">Quick Comparison</h3>
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-gray-500 border-b border-gray-800">
                  <th className="pb-2 pr-4">Version</th>
                  <th className="pb-2 pr-4">User Effort</th>
                  <th className="pb-2 pr-4">Personalization</th>
                  <th className="pb-2 pr-4">Learning</th>
                  <th className="pb-2">Best For</th>
                </tr>
              </thead>
              <tbody className="text-gray-300">
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">AF-01</td>
                  <td className="py-2 pr-4">Low</td>
                  <td className="py-2 pr-4">Basic</td>
                  <td className="py-2 pr-4 text-gray-500">None</td>
                  <td className="py-2">Quick generation</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">GT-01</td>
                  <td className="py-2 pr-4">Low</td>
                  <td className="py-2 pr-4">Basic</td>
                  <td className="py-2 pr-4 text-gray-500">None</td>
                  <td className="py-2">Quality-focused users</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">FP-01</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High</td>
                  <td className="py-2 pr-4 text-gray-500">None</td>
                  <td className="py-2">Guided discovery</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">FP-02</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Improving results</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">FP-03</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Conversational UX</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">AP-01</td>
                  <td className="py-2 pr-4">Low</td>
                  <td className="py-2 pr-4">High</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Emotional processing</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">AP-02</td>
                  <td className="py-2 pr-4">Minimal</td>
                  <td className="py-2 pr-4">Adaptive</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Exploration</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">CS-01</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">Highest</td>
                  <td className="py-2 pr-4 text-emerald-400">Profile + swipes</td>
                  <td className="py-2">Deep personalization</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">FO-01</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High</td>
                  <td className="py-2 pr-4 text-gray-500">None</td>
                  <td className="py-2">Complete onboarding</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">FO-02</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High (iterative)</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Onboarding with learning</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">FO-03</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High (iterative)</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Low-friction onboarding</td>
                </tr>
                <tr className="border-b border-gray-800/50">
                  <td className="py-2 pr-4 font-mono text-purple-400">FO-04</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High (iterative)</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Dynamic AI onboarding</td>
                </tr>
                <tr>
                  <td className="py-2 pr-4 font-mono text-purple-400">FO-05</td>
                  <td className="py-2 pr-4">Medium</td>
                  <td className="py-2 pr-4">High (iterative)</td>
                  <td className="py-2 pr-4 text-emerald-400">From swipes</td>
                  <td className="py-2">Sentence fragment input</td>
                </tr>
              </tbody>
            </table>
          </div>
        </footer>
      </div>
    </div>
  );
}
